#!/bin/bash

source lib

# Check if docker is running
if ! docker info >/dev/null 2>&1; then
     echo "Docker is not running. Please start docker before running tests."
     exit 1
fi

# Start Fusionizer server in docker container
echo -n "Starting Fusionizer server... "
container_id=$(
     docker run \
          -e ADDRESS=$(hostname -I | awk '{print $1}') \
          -p 8000:8000 \
          -v /var/run/docker.sock:/var/run/docker.sock \
          -d ghcr.io/marvin-steinke/nuclio-fusionizer:latest
)
if [ $? -eq 0 ]; then
     echo "done."
else
     echo "error: $container_id" >&2
     exit 1
fi

# Copy config file
echo -n "Copying config.json to server... "
response=$(docker cp config.json $container_id:/app/config.json)
if [ $? -eq 0 ]; then
     echo "done."
else
     echo "error: $response" >&2
     cleanup
     exit 1
fi

# Wait for server to start
echo -n "Waiting for server to start... "
sleep 5
echo -e "done.\n"

# Deploy Tasks
deploy_task "TaskA"
echo ""
deploy_task "TaskB"
echo ""

# Invoke Task A before fusion (Task A has no args)
echo -n "Invoking Task A before fusion (5+3)... "
response=$(curl -s -X POST http://localhost:8000/taska)
echo "done. Task A returns: $response"

# Wait for fusion
echo -n "Waiting for Task A and B to be fused... "
wait_until "TaskA" "fused"
echo -n "done. "
task_info "TaskA"

# Invoke Task A after fusion
echo -n "Invoking Task A after fusion (5+3)... "
response=$(curl -s -X POST http://localhost:8000/taska)
echo -e "done. Task A returns: It's still $response\n"

# Delete Task A
echo -n "Deleting Task A... "
response=$(curl -s -X DELETE http://localhost:8000/taska)
echo -n "done. "
task_info "TaskA"
echo ""

# Now check Task B. Since Task A was deleted, the Fusion Group has to be re-deployed
echo -n "Waiting for redeployment of Fusion Group with Task B... "
wait_until "TaskB" "available"
echo -e "done. "
task_info "TaskB"

# Invoke Task B
echo -n "Invoking Task B after re-deployment (4+8)... "
response=$(
     curl -s -X POST http://localhost:8000/taskb \
          -H "Content-Type: application/json" \
          -d '{"value1": 4, "value2": 8}'
)
echo -e "done. Task B returns: $response\n"

# Delete Task A
echo -n "Deleting Task B... "
response=$(curl -s -X DELETE http://localhost:8000/taskb)
echo -n "done. "
task_info "TaskA"

cleanup

# Compare test logs with reference logs, ignoring addresses and dates.
echo -en "\nComparing test logs with reference logs... "
result=$(
     diff <(cut -d '|' -f 2- logs.txt | sed 's/http:\/\/[0-9.]*:[0-9]*//g') \
          <(cut -d '|' -f 2- ref_logs.txt | sed 's/http:\/\/[0-9.]*:[0-9]*//g')
)
if [ -z "$result" ]; then
     echo "done. No differences found"
else
     echo -e "warning. Differences found:\n$result"
fi
