#!/bin/bash

# ZIP Task A
cd TaskA;zip TaskA.zip -r .;mv TaskA.zip ..;cd ..
# Deploy Task A
curl -X PUT http://localhost:8000/taska \
     -H "Content-Type: multipart/form-data" \
     -F "zip_file=@TaskA.zip"                      

# ZIP Task B
cd TaskB;zip TaskB.zip -r .;mv TaskB.zip ..;cd ..;
# Deploy Task B
curl -X PUT http://localhost:8000/taskb \
     -H "Content-Type: multipart/form-data" \
     -F "zip_file=@TaskB.zip"

# Invoke Task A (Task A has no args)
#curl -X POST http://localhost:8000/taska