apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: nuclio
  name: nuctl-enabler
rules:
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["*"]
  - apiGroups: ["nuclio.io"]
    resources:
      [
        "nucliofunctions",
        "nuclioprojects",
        "nucliofunctionevents",
        "nuclioapigateways",
      ]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["list"]
  - apiGroups: [""]
    resources:
      ["services", "configmaps", "pods", "pods/log", "events", "secrets"]
    verbs: ["*"]
  - apiGroups: ["apps", "extensions"]
    resources: ["deployments"]
    verbs: ["*"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["*"]
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["*"]
  - apiGroups: ["metrics.k8s.io", "custom.metrics.k8s.io"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["*"]