apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nuctl-binding
  namespace: nuclio
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nuctl-enabler
subjects:
- kind: ServiceAccount
  name: nuctl-sa
  namespace: nuclio